### ISSUE TITLE
interface connection

### ISSUE THREAD

**Issue by ra1nb0w** [mmtrt/wine-platform#3]
Sorry for the noise and thank you for your work!
I did a little [snap](https://github.com/ra1nb0w/mikrotik-winbox-snap), using pspad as template. It works but unfortunately when I install it doesn't connect to the wine-platform snap. I re-read many times the documentation and the `snapcraft.yaml` but without success. Have you already encountered this sort of issue?
Thank you

```
You need to connect this snap to the wine-platform snap.

snap install wine-platform
snap connect mikrotik-winbox:wine-platform-plug wine-platform:wine-base-stable
```

**Comment by mmtrt** [comment]
I think some user had reported for a snap that it did not auto connect on first run at that time I did not payed attention to that issue my bad. I guess I'll have to request it for auto connections on snap store but it will need some changes to this snap and to consumer snap.

**Comment by mmtrt** [comment]
Can you try adding `wine-platform-plug` inplace of https://github.com/ra1nb0w/mikrotik-winbox-snap/blob/0437ccd1f76a468eabcdc585b58a1a8c3176fb81/snap/snapcraft.yaml#L45 see if that does anything.

**Comment by ra1nb0w** [comment]
Thank you for your attention. Yes, probably something to enable on snap store; maybe related to `canonical✓` a verify process.

with `wine-platform-plug` on `stage` i receive the following error
```
Cleaning later steps and re-staging mikrotik-winbox ('stage' property changed)
Failed to copy '/root/parts/mikrotik-winbox/install/wine-platform-plug': no such file or directory.
Check the path and try again.
```

**Comment by mmtrt** [comment]
I've posted auto connection request which is currently waiting to be reviewed [link](https://forum.snapcraft.io/t/auto-connections-of-wine-base-stable-wine-base-devel-and-wine-base-staging/11229)

**Comment by ra1nb0w** [comment]
thank you!

**Comment by mmtrt** [comment]
Request have been approved so now you have to migrate your snap to new wine platform snaps in order to use auto-connections of the interfaces. I will migrate all my snaps to use new wine platform snaps though I have a single snap migrated atm https://github.com/mmtrt/notepad3

**Comment by ra1nb0w** [comment]
thank you!

**Comment by ra1nb0w** [comment]
I finally had the time to update my snap; unfortunately, the snap continue to need the manually connection to `wine-runtime` and `wine-3-stable`.

`snap list` show
```
wine-platform-3-stable  3.0.4            6     stable       mmtrt        -
wine-platform-runtime   v1.0             6     stable       mmtrt        -
```
without the tick that confirm the auto connection. I just [changed](https://github.com/ra1nb0w/mikrotik-winbox-snap/commit/be703affd65254261509574021d525f1d8ed9c79) the code following your commit. I already tried to remove/install `wine-platform-3-stable` and `wine-platform-runtime`.

Suggestions?

thanks

**Comment by mmtrt** [comment]
what `snap connections mikrotik-winbox` say and also make sure you have installed your snap from store and not have local built snap installed which may not autoconnect to platform snaps.

if snap connections say manual to my platform snaps then disconnect them manually and then remove my snaps and your as well that will delete your snap saved data take caution.

I think it is working though I'm not sure since it could not completed that step as I lost internet connection.
```
sudo snap install --edge mikrotik-winbox
[sudo] password for mmtrt: 
Automatically connect eligible plugs and slots of snap "mikrotik-winbox" 
```

Also make sure you try to install your snap on fresh os install for sake of testing this maybe vm or something.
* install snapd if os does not provides ootb
* snap install core core18
* snap install mikrotik-winbox <---- use the snap branch which have your latest changes 

EDIT: it did not auto connect it as it did for `icon-themes`, I'll ask on topic why it did not

**Comment by ra1nb0w** [comment]
from clean ubuntu 18.04, command `snap connections mikrotik-winbox`
```
Interface             Plug                             Slot                           Notes
content[icon-themes]  mikrotik-winbox:icon-themes      gtk-common-themes:icon-themes  -
content               mikrotik-winbox:wine-3-stable    -                              -
content               mikrotik-winbox:wine-runtime     -                              -
desktop               mikrotik-winbox:desktop          :desktop                       -
desktop-legacy        mikrotik-winbox:desktop-legacy   :desktop-legacy                -
home                  mikrotik-winbox:home             :home                          -
network               mikrotik-winbox:network          :network                       -
removable-media       mikrotik-winbox:removable-media  -                              -
wayland               mikrotik-winbox:wayland          :wayland                       -
x11                   mikrotik-winbox:x11              :x11                           -
```

sorry, but it is not clear to me your edit: icon-themes connect correctly but wine-platform-* fail and you need to ask upstream why; correct?

**Comment by mmtrt** [comment]
Yeah I'll post.

**Comment by ra1nb0w** [comment]
Any news?

**Comment by mmtrt** [comment]
`snapd` dev have confirmed getting the same behavior as us regarding auto connections and asked other dev to check for any regressions in `snapd` for it.

**Comment by ra1nb0w** [comment]
Thank you for the update. so, we wait upstream..

**Comment by ra1nb0w** [comment]
any news from upstream?

**Comment by mmtrt** [comment]
Dev had posted `I’ll investigate this next week.` since that 17d past no response atm. I'll bump the thread.

**Comment by ra1nb0w** [comment]
Quite unreliable the upstream :)

**Comment by mmtrt** [comment]
They had fixed this issue on Mar 2020 though it took quite some time, from what I see you have taken down this snap still if you have it in your account you can make changes and build up.

Also I'm sorry for being pretty late to inform you about this I thought about it after a user requested for snap of this app on [forum](https://forum.snapcraft.io/t/mikrotik-winbox-the-dude-netinstall-bandwidth-test/22876).
